name: data_collector
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  sensors_plus: ^5.0.1
  logger: ^2.4.0
  geolocator: ^12.0.0
  device_info_plus: ^10.1.0
  environment_sensors: ^0.3.0
  network_info_plus: ^5.0.3
  wifi_iot: ^0.3.19
  pedometer: ^4.0.1
  flutter_activity_recognition: ^3.1.0
  real_volume: ^1.0.8
  is_lock_screen2: ^2.0.1
  keep_screen_on: ^3.0.0
  battery_plus: ^6.0.1
  phone_state: ^1.0.4
  path_provider: ^2.1.3
  external_path: ^1.0.3
  appcheck: ^1.5.1
  app_usage: ^3.0.1
  flutter_blue_plus: ^1.32.8
  flutter_background_service: ^5.0.6
  location: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true